version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app_comment
        volumes:
            - .:/var/www
        depends_on:
            - db
            - elasticsearch
            - rabbitmq
        networks:
            - laravel_network
        command: supervisord -c /etc/supervisor/conf.d/supervisord.conf

    nginx:
        image: nginx:latest
        container_name: nginx_web_laravel
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www
        depends_on:
            - app
        networks:
            - laravel_network

    db:
        image: mysql:8.0
        container_name: mysql_db_laravel
        environment:
            MYSQL_DATABASE: comment_system
            MYSQL_USER:  user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel_network

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        container_name: elasticsearch_laravel
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - laravel_network

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - laravel_network

networks:
    laravel_network:
        driver: bridge

volumes:
    db_data:
